In [108]:
from sklearn.datasets import load_breast_cancer

from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Dense

In [65]:
!pip install TensorFlow

  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 3.10.0
    Uninstalling importlib-metadata-3.10.0:
      Successfully uninstalled importlib-metadata-3.10.0
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached tensorboard-2.10.1-py3-none-any.whl (5.9 MB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached grpcio-1.50.0-cp38-cp38-win_amd64.whl (3.7 MB)
  Using cached libclang-14.0.6-py2.py3-none-win_amd64.whl (14.2 MB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached protobuf-3.19.6-cp38-cp38-win_amd64.whl (896 kB)
  Using cached absl_py-1.3.0-py3-none-any.whl (124 kB)
  Using cached tensorflow_io_gcs_filesystem-0.27.0-cp38-cp38-win_amd64.whl (1.5 MB)
  Using cached flatbuffers-22.10.26-py2.py3-none-any.whl (26 kB)
  Using cached tensorflow_estimator-2.10.0-py2.py3-none-any.whl (438 kB)
  Using cached termcolor

  Using cached google_auth-2.14.1-py2.py3-none-any.whl (175 kB)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
  Using cached importlib_metadata-5.0.0-py3-none-any.whl (21 kB)
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 3.10.0
    Can't uninstall 'importlib-metadata'. No files were found to uninstall.


In [64]:
!pip install Keras

In [2]:
data = load_breast_cancer()

In [3]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
 data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [8]:
descr = data['DESCR']
print(descr)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [9]:
print(data['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [10]:
data['data'].shape

(569, 30)

In [12]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [13]:
data['data'][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [16]:
j = 0
for i in data['feature_names']:
    print(i,':',data['data'][0][j])
    j += 1

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


In [17]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [18]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [19]:
data['target'].shape

(569,)

In [20]:
data['filename']

'C:\\Users\\MANOJ\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\breast_cancer.csv'

In [23]:
feature = data['data']
feature.shape

(569, 30)

In [139]:
label = data['target']
label.shape

(569,)

In [26]:
print(descr)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [28]:
scale = StandardScaler()

feature = scale.fit_transform(feature)

In [30]:
j = 0
for i in data['feature_names']:
    print(i,':',feature[0][j])
    j += 1

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [37]:
print(feature[0])
print(data['target_names'][label[0]],':', label[0])

[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]
malignant : 0


In [39]:
print(feature[20])
print(data['target_names'][label[20]],':', label[20])

[-0.29744572 -0.83300824 -0.26110605 -0.38363845  0.79276301  0.42942187
 -0.54136176 -0.45962673  0.56728859  0.75308658 -0.79392535 -0.85120566
 -0.73415971 -0.56471962 -0.98136609 -0.36317799 -0.49449443 -0.86070672
 -0.4555335  -0.51816798 -0.3663683  -0.84470709 -0.33274394 -0.43962431
 -0.05122636  0.14844292 -0.39909871 -0.63610973  0.45822712 -0.11724974]
benign : 1


In [43]:
df = pd.DataFrame(feature, columns = data['feature_names'])
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0       1.097064     -2.073335        1.269934   0.984375         1.568466   
1       1.829821     -0.353632        1.685955   1.908708        -0.826962   
2       1.579888      0.456187        1.566503   1.558884         0.942210   
3      -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4       1.750297     -1.151816        1.776573   1.826229         0.280372   
..           ...           ...             ...        ...              ...   
564     2.110995      0.721473        2.060786   2.343856         1.041842   
565     1.704854      2.085134        1.615931   1.723842         0.102458   
566     0.702284      2.045574        0.672676   0.577953        -0.840484   
567     1.838341      2.336457        1.982524   1.735218         1.525767   
568    -1.808401      1.221792       -1.814389  -1.347789        -3.112085   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0            3.283515        2.652874             2.532475       2.217515   
1           -0.487072       -0.023846             0.548144       0.001392   
2            1.052926        1.363478             2.037231       0.939685   
3            3.402909        1.915897             1.451707       2.867383   
4            0.539340        1.371011             1.428493      -0.009560   
..                ...             ...                  ...            ...   
564          0.219060        1.947285             2.320965      -0.312589   
565         -0.017833        0.693043             1.263669      -0.217664   
566         -0.038680        0.046588             0.105777      -0.809117   
567          3.272144        3.296944             2.658866       2.137194   
568         -1.150752       -1.114873            -1.261820      -0.820070   

     mean fractal dimension  ...  worst radius  worst texture  \
0                  2.255747  ...      1.886690      -1.359293   
1                 -0.868652  ...      1.805927      -0.369203   
2                 -0.398008  ...      1.511870      -0.023974   
3                  4.910919  ...     -0.281464       0.133984   
4                 -0.562450  ...      1.298575      -1.466770   
..                      ...  ...           ...            ...   
564               -0.931027  ...      1.901185       0.117700   
565               -1.058611  ...      1.536720       2.047399   
566               -0.895587  ...      0.561361       1.374854   
567                1.043695  ...      1.961239       2.237926   
568               -0.561032  ...     -1.410893       0.764190   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0           2.303601    2.001237          1.307686           2.616665   
1           1.535126    1.890489         -0.375612          -0.430444   
2           1.347475    1.456285          0.527407           1.082932   
3          -0.249939   -0.550021          3.394275           3.893397   
4           1.338539    1.220724          0.220556          -0.313395   
..               ...         ...               ...                ...   
564         1.752563    2.015301          0.378365          -0.273318   
565         1.421940    1.494959         -0.691230          -0.394820   
566         0.579001    0.427906         -0.809587           0.350735   
567         2.303601    1.653171          1.430427           3.904848   
568        -1.432735   -1.075813         -1.859019          -1.207552   

     worst concavity  worst concave points  worst symmetry  \
0           2.109526              2.296076        2.750622   
1          -0.146749              1.087084       -0.243890   
2           0.854974              1.955000        1.152255   
3           1.989588              2.175786        6.046041   
4           0.613179              0.729259       -0.868353   
..               ...                   ...             ...   
564         0.664512              1.629151       -1

In [52]:
#500 Training

X_train = feature[:500]
Y_train = label[:500]

#35 Validation

X_val = feature[500:535]
Y_val = label[500:535]

#34 Testing

X_test = feature[535:]
Y_test = label[535:]


In [50]:
feature[:500].shape

(500, 30)

In [57]:
print(X_train.shape)
print(Y_train.shape)

(500, 30)
(500,)


In [58]:
print(X_val.shape)
print(Y_val.shape)

(35, 30)
(35,)


In [59]:
Y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [90]:
model = Sequential()

model.add(Dense(15, activation = 'relu', input_dim = 30 ))
model.add(Dense(8 , activation = 'relu'))
model.add(Dense(1 , activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [102]:
model.fit(X_train, Y_train, batch_size = 1, epochs = 5, validation_data = (X_val, Y_val))

Epoch 1/5
500/500 [==============================] - 2s 5ms/step - loss: 0.0081 - accuracy: 0.9980 - val_loss: 0.1737 - val_accuracy: 0.9714
Epoch 2/5
500/500 [==============================] - 2s 5ms/step - loss: 0.0055 - accuracy: 1.0000 - val_loss: 0.1259 - val_accuracy: 0.9714
Epoch 3/5
500/500 [==============================] - 2s 4ms/step - loss: 0.0051 - accuracy: 1.0000 - val_loss: 0.1858 - val_accuracy: 0.9714
Epoch 4/5
500/500 [==============================] - 2s 4ms/step - loss: 0.0078 - accuracy: 0.9980 - val_loss: 0.1558 - val_accuracy: 0.9714
Epoch 5/5
500/500 [==============================] - 2s 4ms/step - loss: 0.0040 - accuracy: 1.0000 - val_loss: 0.0895 - val_accuracy: 0.9714


In [103]:
model.evaluate(X_test, Y_test)

2/2 [==============================] - 0s 6ms/step - loss: 0.0353 - accuracy: 0.9706


[0.035327307879924774, 0.970588207244873]

In [104]:
model.evaluate(X_val, Y_val)

2/2 [==============================] - 0s 6ms/step - loss: 0.0895 - accuracy: 0.9714


[0.08950041979551315, 0.9714285731315613]

In [121]:
sample = X_test[10]

In [122]:
sample.shape

(30,)

In [123]:
sample

array([-0.14407806,  0.91694624, -0.19684934, -0.23233219, -0.27756523,
       -0.6987597 , -0.741488  , -0.6316726 , -0.53894726, -0.67869351,
       -0.21356438,  0.21617286, -0.39605381, -0.20015129, -0.39100882,
       -0.25084001, -0.38739725, -0.44317904,  0.03967757, -0.45840426,
       -0.19034815,  0.55574951, -0.28836304, -0.26506358, -0.47205092,
       -0.65245698, -0.80257043, -0.65270672, -0.41860997, -0.7988643 ])

In [124]:
sample = np.reshape(sample, (1,30))
sample.shape

(1, 30)

In [125]:
model.predict(sample)

1/1 [==============================] - 0s 54ms/step


array([[0.9990184]], dtype=float32)

In [126]:
model.predict(sample)[0][0]

1/1 [==============================] - 0s 46ms/step


0.9990184

In [127]:
#Malignant - 0
#Benign - 1

In [128]:
if model.predict(sample)[0][0] > 0.5:
    print("Benign")
else:
    print('Malignant')

1/1 [==============================] - 0s 70ms/step
Benign


In [130]:
Y_test[10]

1

In [136]:
for i in range (10):
    
    sample = X_test[i]

    sample = np.reshape(sample, (1,30))
    
    #print('Predicted' = -)

    if model.predict(sample)[0][0] > 0.5:
        print("-Benign")
    else:
        print('-Malignant')
        
    #print('Actual' = *)
        
    if Y_test[i] == 1:
        print("*Benign")
    else:
        print('*Malignant')
        
    print('---------')

1/1 [==============================] - 0s 45ms/step
-Malignant
*Malignant
---------
1/1 [==============================] - 0s 41ms/step
-Malignant
*Malignant
---------
1/1 [==============================] - 0s 53ms/step
-Benign
*Benign
---------
1/1 [==============================] - 0s 41ms/step
-Benign
*Benign
---------
1/1 [==============================] - 0s 41ms/step
-Benign
*Benign
---------
1/1 [==============================] - 0s 40ms/step
-Benign
*Benign
---------
1/1 [==============================] - 0s 53ms/step
-Malignant
*Benign
---------
1/1 [==============================] - 0s 66ms/step
-Benign
*Benign
---------
1/1 [==============================] - 0s 45ms/step
-Benign
*Benign
---------
1/1 [==============================] - 0s 42ms/step
-Benign
*Benign
---------


In [142]:
label = data['target']

In [144]:
df_frt = pd.DataFrame(feature, columns = data['feature_names'])
df_lbl = pd.DataFrame(label, columns = ['label'])
df = pd.concat([df_frt, df_lbl], axis = 1)
df = df.sample(frac = 1)

In [145]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
83      1.412320      1.629029        1.529432   1.356952         1.789079   
33      1.460602      1.670916        1.480004   1.442275        -0.167259   
28      0.333066      1.391668        0.429654   0.220449         0.842579   
280     1.429361      1.701168        1.409980   1.374017         0.401353   
429    -0.399691     -0.376903       -0.452640  -0.436823        -1.238299   
..           ...           ...             ...        ...              ...   
386    -0.544538     -1.209993       -0.543259  -0.548596        -1.087428   
499     1.835501      0.453860        1.887787   1.891644         0.863928   
224    -0.243483     -0.528162       -0.305591  -0.308554        -0.847600   
243    -0.107156      1.042608       -0.141243  -0.184551        -1.133686   
493    -0.473535     -1.503204       -0.541199  -0.505082        -1.611206   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
83           1.416794        1.317025             2.527316      -0.648476   
33           1.280343        0.965486             0.696717       0.151081   
28           1.238650        0.998129             0.995412       0.417600   
280          0.776234        1.296937             1.230911       0.329977   
429         -1.120430       -0.938852            -0.788500      -1.287391   
..                ...             ...                  ...            ...   
386         -0.494842       -0.256238            -0.608200      -0.604664   
499          1.138207        1.632155             1.629686       0.132826   
224         -1.030979       -0.668669            -0.628319      -1.152306   
243         -0.687389       -0.525166            -0.657209      -0.140994   
493         -1.211208       -1.024816            -0.965447      -0.725145   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
83                 1.338557  ...       1.146872         1.013874    0.733782   
33                -0.026596  ...       0.850497         1.612569    1.639107   
28                 0.368916  ...       1.796619         1.252161    0.682803   
280               -0.084717  ...       1.664716         1.564912    1.482653   
429               -1.043018  ...      -0.768171        -0.547798   -0.516445   
..                      ...  ...            ...              ...         ...   
386               -0.178279  ...      -1.040120        -0.584136   -0.616470   
499               -0.081882  ...       0.827699         1.666184    1.545938   
224               -0.858729  ...      -0.338263        -0.250833   -0.301980   
243               -1.206042  ...       0.107929        -0.275853   -0.306902   
493               -0.378161  ...      -1.517252        -0.715492   -0.609263   

     worst smoothness  worst compactness  worst concavity  \
83           0.299461           0.174525        -0.139073   
33           0.812341           2.574680         1.616341   
28           1.390974           2.269333         1.733401   
280          2.009061           0.825932         1.454664   
429         -1.120822          -1.006469        -1.139405   
..                ...                ...              ...   
386         -1.304933          -0.071025         0.169888   
499          0.615079           0.670714         1.178807   
224         -0.209036          -0.783502        -0.448993   
243         -1.695949          -0.700167        -0.653847   
493         -1.664826          -1.205453        -1.225520   

     worst concave points  worst symmetry  worst fractal dimension  label  
83               1.058154       -0.954095                 0.447992      0  
33               0.972885        1.247704                 1.571270      0  
28               1.336800        1.822016                 0.820940      0  
280              1.105356        0.577943                 0.734491      0  
429             -1.195078       -1.190291                -1.313123   